version: '3'

services:
  db:
    image: postgres:latest
    container_name: JustGolfContainer_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  web:
    build: .
    container_name: JustGolfContainer_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DJANGO_DB_HOST: ${DATABASE_HOST}
      DJANGO_DB_PORT: ${DATABASE_PORT}
      DJANGO_DB_NAME: ${DATABASE_NAME}
      DJANGO_DB_USER: ${DATABASE_USER}
      DJANGO_DB_PASSWORD: ${DATABASE_PASSWORD}
